const build = await Bun.build({
  entrypoints: [new URL("../cli/index.ts", import.meta.url).pathname],
  target: "bun",
  format: "esm",
  minify: false,
  sourcemap: "none",
});
if (!build.success || !build.outputs[0]) {
  throw new Error(build.logs.map(String).join("\n") || "CLI build failed");
}
const builtCli = (await build.outputs[0].text()).replace(/^#![^\n]*\n/, "");
const cli = `#!/usr/bin/env bun\n${builtCli}`;
const setup = await Bun.file(new URL("../src/setup.sh", import.meta.url)).text();

function moduleSource(label: string, value: string): string {
  return `// generated by scripts/gen-distribution.ts from ${label} — do not edit\nexport default ${JSON.stringify(Buffer.from(value).toString("base64"))};\n`;
}

await Promise.all([
  Bun.write(new URL("../src/cli.generated.ts", import.meta.url), moduleSource("cli/index.ts", cli)),
  Bun.write(new URL("../src/setup-sh.generated.ts", import.meta.url), moduleSource("src/setup.sh", setup)),
]);
console.log("generated distributable CLI and setup script");
