#!/usr/bin/env bun
const platformRoot = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const dashboardRoot = `${platformRoot}/src/dashboard`;
const generatedPath = `${platformRoot}/src/dashboard-assets.generated.ts`;

const MAX_JS_BYTES = 2 * 1024 * 1024;
const MAX_CSS_BYTES = 1024 * 1024;

function validateAsset(label: string, value: string, maximumBytes: number): void {
  if (!value.trim()) throw new Error(`${label} build produced empty output`);
  const bytes = Buffer.byteLength(value);
  if (bytes > maximumBytes) {
    throw new Error(`${label} build is ${bytes} bytes, exceeding the ${maximumBytes}-byte ceiling`);
  }
}

function etag(value: string): string {
  const hash = new Bun.CryptoHasher("sha256").update(value).digest("hex");
  return `"sha256-${hash}"`;
}

async function inlineFontAssets(css: string): Promise<string> {
  const fontUrls = [...css.matchAll(/url\((?:"|')?\.\/files\/([^"')]+)(?:"|')?\)/g)];
  let output = css;
  for (const [url, filename] of fontUrls) {
    if (!filename || !/^[a-z0-9-]+\.woff2$/.test(filename)) {
      throw new Error(`unexpected dashboard font URL: ${url}`);
    }
    const font = await Bun.file(`${platformRoot}/node_modules/@fontsource-variable/inter/files/${filename}`).bytes();
    output = output.replaceAll(url, `url(data:font/woff2;base64,${Buffer.from(font).toString("base64")})`);
  }
  const externalUrl = [...output.matchAll(/url\(([^)]+)\)/g)]
    .map((match) => match[1]?.replace(/^(?:"|')|(?:"|')$/g, ""))
    .find((url) => url && !url.startsWith("data:"));
  if (externalUrl) throw new Error(`dashboard CSS contains an external asset URL: ${externalUrl}`);
  return output;
}

const dashboardAliasPlugin: Bun.BunPlugin = {
  name: "dashboard-alias",
  setup(build) {
    build.onResolve({ filter: /^@\// }, ({ path }) => ({
      path: Bun.resolveSync(`${dashboardRoot}/${path.slice(2)}`, platformRoot),
    }));
  },
};

function generatedModule(javaScript: string, css: string): string {
  return [
    "// generated by scripts/gen-dashboard.ts — do not edit",
    `export const DASHBOARD_JS = ${JSON.stringify(javaScript)};`,
    `export const DASHBOARD_JS_ETAG = ${JSON.stringify(etag(javaScript))};`,
    `export const DASHBOARD_CSS = ${JSON.stringify(css)};`,
    `export const DASHBOARD_CSS_ETAG = ${JSON.stringify(etag(css))};`,
    "",
  ].join("\n");
}

const javaScriptBuild = await Bun.build({
  entrypoints: [`${dashboardRoot}/main.tsx`],
  target: "browser",
  format: "esm",
  root: platformRoot,
  minify: true,
  sourcemap: "none",
  define: { "process.env.NODE_ENV": JSON.stringify("production") },
  tsconfig: `${platformRoot}/tsconfig.dashboard.json`,
  plugins: [dashboardAliasPlugin],
});
if (!javaScriptBuild.success || javaScriptBuild.outputs.length !== 1) {
  throw new Error(javaScriptBuild.logs.map(String).join("\n") || "dashboard JavaScript build failed");
}
const javaScript = await javaScriptBuild.outputs[0]!.text();

// Tailwind's --output defaults to `-`, so the stylesheet comes back on stdout.
const compiledCss = await Bun.$`${platformRoot}/node_modules/.bin/tailwindcss --input ${dashboardRoot}/styles.css --minify`
  .cwd(platformRoot)
  .text();
const css = await inlineFontAssets(compiledCss);

validateAsset("dashboard JavaScript", javaScript, MAX_JS_BYTES);
validateAsset("dashboard CSS", css, MAX_CSS_BYTES);
await Bun.write(generatedPath, generatedModule(javaScript, css));

console.log(
  `generated dashboard assets (${Buffer.byteLength(javaScript)} bytes JS, ${Buffer.byteLength(css)} bytes CSS)`,
);
